CREATE TABLE "orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"fulfillment_status" text DEFAULT 'not_ready' NOT NULL,
	"items" jsonb NOT NULL,
	"amount" integer NOT NULL,
	"currency" text NOT NULL,
	"razorpay_order_id" text,
	"razorpay_payment_id" text,
	"provider_payment_status" text,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"paid_at" text,
	"last_error" text,
	CONSTRAINT "orders_reference_unique" UNIQUE("reference"),
	CONSTRAINT "orders_razorpay_order_id_unique" UNIQUE("razorpay_order_id"),
	CONSTRAINT "orders_razorpay_payment_id_unique" UNIQUE("razorpay_payment_id"),
	CONSTRAINT "orders_status_check" CHECK ("orders"."status" in ('pending', 'paid')),
	CONSTRAINT "orders_fulfillment_status_check" CHECK ("orders"."fulfillment_status" in ('not_ready', 'unfulfilled', 'fulfilled')),
	CONSTRAINT "orders_amount_check" CHECK ("orders"."amount" > 0),
	CONSTRAINT "orders_currency_check" CHECK ("orders"."currency" = 'INR'),
	CONSTRAINT "orders_paid_state_check" CHECK (("orders"."status" = 'pending' and "orders"."paid_at" is null and "orders"."fulfillment_status" = 'not_ready') or ("orders"."status" = 'paid' and "orders"."paid_at" is not null and "orders"."razorpay_payment_id" is not null and "orders"."fulfillment_status" in ('unfulfilled', 'fulfilled')))
);
