/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoryAllProductsRouteImport } from './routes/category.all-products'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiQuotesIndexRouteImport } from './routes/api/quotes/index'
import { Route as ApiQuotesQuoteIdRouteImport } from './routes/api/quotes/$quoteId'
import { Route as ApiQuotesDevPreviewRouteImport } from './routes/api/quotes/dev-preview'
import { Route as ApiQuotesDevTestRouteImport } from './routes/api/quotes/dev-test'
import { Route as ApiRazorpayOrderRouteImport } from './routes/api/razorpay/order'
import { Route as ApiRazorpayVerifyRouteImport } from './routes/api/razorpay/verify'
import { Route as ApiQuotesQuoteIdStatusRouteImport } from './routes/api/quotes/$quoteId/status'
import { Route as ApiQuotesQuoteIdSubmitRouteImport } from './routes/api/quotes/$quoteId/submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryAllProductsRoute = CategoryAllProductsRouteImport.update({
  id: '/category/all-products',
  path: '/category/all-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesIndexRoute = ApiQuotesIndexRouteImport.update({
  id: '/api/quotes/',
  path: '/api/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesQuoteIdRoute = ApiQuotesQuoteIdRouteImport.update({
  id: '/api/quotes/$quoteId',
  path: '/api/quotes/$quoteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesDevPreviewRoute = ApiQuotesDevPreviewRouteImport.update({
  id: '/api/quotes/dev-preview',
  path: '/api/quotes/dev-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesDevTestRoute = ApiQuotesDevTestRouteImport.update({
  id: '/api/quotes/dev-test',
  path: '/api/quotes/dev-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayOrderRoute = ApiRazorpayOrderRouteImport.update({
  id: '/api/razorpay/order',
  path: '/api/razorpay/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayVerifyRoute = ApiRazorpayVerifyRouteImport.update({
  id: '/api/razorpay/verify',
  path: '/api/razorpay/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesQuoteIdStatusRoute = ApiQuotesQuoteIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiQuotesQuoteIdRoute,
} as any)
const ApiQuotesQuoteIdSubmitRoute = ApiQuotesQuoteIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiQuotesQuoteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/category/all-products': typeof CategoryAllProductsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/quotes/$quoteId': typeof ApiQuotesQuoteIdRouteWithChildren
  '/api/quotes/dev-preview': typeof ApiQuotesDevPreviewRoute
  '/api/quotes/dev-test': typeof ApiQuotesDevTestRoute
  '/api/razorpay/order': typeof ApiRazorpayOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/api/quotes/': typeof ApiQuotesIndexRoute
  '/api/quotes/$quoteId/status': typeof ApiQuotesQuoteIdStatusRoute
  '/api/quotes/$quoteId/submit': typeof ApiQuotesQuoteIdSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/category/all-products': typeof CategoryAllProductsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/quotes/$quoteId': typeof ApiQuotesQuoteIdRouteWithChildren
  '/api/quotes/dev-preview': typeof ApiQuotesDevPreviewRoute
  '/api/quotes/dev-test': typeof ApiQuotesDevTestRoute
  '/api/razorpay/order': typeof ApiRazorpayOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/api/quotes': typeof ApiQuotesIndexRoute
  '/api/quotes/$quoteId/status': typeof ApiQuotesQuoteIdStatusRoute
  '/api/quotes/$quoteId/submit': typeof ApiQuotesQuoteIdSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/category/all-products': typeof CategoryAllProductsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/quotes/$quoteId': typeof ApiQuotesQuoteIdRouteWithChildren
  '/api/quotes/dev-preview': typeof ApiQuotesDevPreviewRoute
  '/api/quotes/dev-test': typeof ApiQuotesDevTestRoute
  '/api/razorpay/order': typeof ApiRazorpayOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/api/quotes/': typeof ApiQuotesIndexRoute
  '/api/quotes/$quoteId/status': typeof ApiQuotesQuoteIdStatusRoute
  '/api/quotes/$quoteId/submit': typeof ApiQuotesQuoteIdSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/category/all-products'
    | '/product/$slug'
    | '/api/quotes/$quoteId'
    | '/api/quotes/dev-preview'
    | '/api/quotes/dev-test'
    | '/api/razorpay/order'
    | '/api/razorpay/verify'
    | '/api/quotes/'
    | '/api/quotes/$quoteId/status'
    | '/api/quotes/$quoteId/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/category/all-products'
    | '/product/$slug'
    | '/api/quotes/$quoteId'
    | '/api/quotes/dev-preview'
    | '/api/quotes/dev-test'
    | '/api/razorpay/order'
    | '/api/razorpay/verify'
    | '/api/quotes'
    | '/api/quotes/$quoteId/status'
    | '/api/quotes/$quoteId/submit'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/category/all-products'
    | '/product/$slug'
    | '/api/quotes/$quoteId'
    | '/api/quotes/dev-preview'
    | '/api/quotes/dev-test'
    | '/api/razorpay/order'
    | '/api/razorpay/verify'
    | '/api/quotes/'
    | '/api/quotes/$quoteId/status'
    | '/api/quotes/$quoteId/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CategoryAllProductsRoute: typeof CategoryAllProductsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiQuotesQuoteIdRoute: typeof ApiQuotesQuoteIdRouteWithChildren
  ApiQuotesDevPreviewRoute: typeof ApiQuotesDevPreviewRoute
  ApiQuotesDevTestRoute: typeof ApiQuotesDevTestRoute
  ApiRazorpayOrderRoute: typeof ApiRazorpayOrderRoute
  ApiRazorpayVerifyRoute: typeof ApiRazorpayVerifyRoute
  ApiQuotesIndexRoute: typeof ApiQuotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/all-products': {
      id: '/category/all-products'
      path: '/category/all-products'
      fullPath: '/category/all-products'
      preLoaderRoute: typeof CategoryAllProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/': {
      id: '/api/quotes/'
      path: '/api/quotes'
      fullPath: '/api/quotes/'
      preLoaderRoute: typeof ApiQuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/$quoteId': {
      id: '/api/quotes/$quoteId'
      path: '/api/quotes/$quoteId'
      fullPath: '/api/quotes/$quoteId'
      preLoaderRoute: typeof ApiQuotesQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/dev-preview': {
      id: '/api/quotes/dev-preview'
      path: '/api/quotes/dev-preview'
      fullPath: '/api/quotes/dev-preview'
      preLoaderRoute: typeof ApiQuotesDevPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/dev-test': {
      id: '/api/quotes/dev-test'
      path: '/api/quotes/dev-test'
      fullPath: '/api/quotes/dev-test'
      preLoaderRoute: typeof ApiQuotesDevTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/order': {
      id: '/api/razorpay/order'
      path: '/api/razorpay/order'
      fullPath: '/api/razorpay/order'
      preLoaderRoute: typeof ApiRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/verify': {
      id: '/api/razorpay/verify'
      path: '/api/razorpay/verify'
      fullPath: '/api/razorpay/verify'
      preLoaderRoute: typeof ApiRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/$quoteId/status': {
      id: '/api/quotes/$quoteId/status'
      path: '/status'
      fullPath: '/api/quotes/$quoteId/status'
      preLoaderRoute: typeof ApiQuotesQuoteIdStatusRouteImport
      parentRoute: typeof ApiQuotesQuoteIdRoute
    }
    '/api/quotes/$quoteId/submit': {
      id: '/api/quotes/$quoteId/submit'
      path: '/submit'
      fullPath: '/api/quotes/$quoteId/submit'
      preLoaderRoute: typeof ApiQuotesQuoteIdSubmitRouteImport
      parentRoute: typeof ApiQuotesQuoteIdRoute
    }
  }
}

interface ApiQuotesQuoteIdRouteChildren {
  ApiQuotesQuoteIdStatusRoute: typeof ApiQuotesQuoteIdStatusRoute
  ApiQuotesQuoteIdSubmitRoute: typeof ApiQuotesQuoteIdSubmitRoute
}

const ApiQuotesQuoteIdRouteChildren: ApiQuotesQuoteIdRouteChildren = {
  ApiQuotesQuoteIdStatusRoute: ApiQuotesQuoteIdStatusRoute,
  ApiQuotesQuoteIdSubmitRoute: ApiQuotesQuoteIdSubmitRoute,
}

const ApiQuotesQuoteIdRouteWithChildren =
  ApiQuotesQuoteIdRoute._addFileChildren(ApiQuotesQuoteIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CategoryAllProductsRoute: CategoryAllProductsRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiQuotesQuoteIdRoute: ApiQuotesQuoteIdRouteWithChildren,
  ApiQuotesDevPreviewRoute: ApiQuotesDevPreviewRoute,
  ApiQuotesDevTestRoute: ApiQuotesDevTestRoute,
  ApiRazorpayOrderRoute: ApiRazorpayOrderRoute,
  ApiRazorpayVerifyRoute: ApiRazorpayVerifyRoute,
  ApiQuotesIndexRoute: ApiQuotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
